diffOpParams: [0.05, 0.05, 0.005]
study:
    I0: /directory_to_repo/data/images/atlas.mhd
    scaleMomenta: 1.0
    m0: /directory_to_m0/m0.mhd
integration:
    nTimeSteps: 20
    NIterForInverse: 5
    integMethod: RK4
io:
    outputPrefix: output_prefix
    gridEvery: 1
    plotSlice: None
    saveFrames: False
    plotSliceDim: z
    quiverEvery: 1
useCUDA: true
